### ISSUE TITLE
Any chance on 5GHz channel support?

### ISSUE THREAD

**Issue by sgaits** [DanMcInerney/wifijammer#29]
Is there any chance of adding channel support for the 5GHz band?  I have been using this for a while and  find it very useful at times.  I am seeing an increase in the 5GHz usage and would like to have it included.  Thanks for the great work!

**Comment by DanMcInerney** [comment]
Yes I would like to add 5GHz. The issue I ran into was figuring out how to
grab the 5GHz channels in scapy in order to switch to that channel. You
seem to just get garbage when you use the same method as getting 2.4Ghz.

**Comment by valherru** [comment]
I really like your script, powerful and simple to use.. great work! And I also would like to ask you for adding 5GHz support if possible...somehow. Or do you have any progress in this? Thank you so much!

**Comment by DanMcInerney** [comment]
I don't have any further progress just yet although I do plan on attempting
to add it in the future. Maybe a few months from now when I have more free
time I'lll take another crack at identifying and changing 5GHz channels
which I think is the only blockade at this point.

**Comment by vxbinaca** [comment]
@DanMcInerney another problem you're going to run into is that many 5GHz capable Alfa devices don't work so well under Linux with current drivers.

Nice work on the script. Twas using it with friends at their house this weekend to great amusement.

**Comment by valherru** [comment]
For Alfa devices maybe with future drivers...but crappy drivers should not affect the script anyway. Right now I have Ubiquiti SR71 USB and it works well with standard carl9170 driver on 5Ghz.

**Comment by alexmerser2016** [comment]
Greetings! Is it possible when using your wonderful program to specify a number of MAC-addresses of access points, from which I do not need to turn off customers? Thank you in advance! Sorry for my English...

**Comment by careyer** [comment]
@DanMcInerney, could you make any progress in 5Ghz support by any chance? Would be great if you could give it a try again since all the tools are available in newer versions by now and also the ALFA 5Ghz drivers for Linux are very reliable by now. Thank you very much in advance

**Comment by MisterBianco** [comment]
I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and see... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.

**Comment by DanMcInerney** [comment]
I haven't checked your tool out yet but I fully endorse rewriting this
script. It was written early in my python learning and I don't really feel
like working on it.

**Comment by MisterBianco** [comment]
That's great to hear I appreciate your enthusiasm about my rewrite, wasn't sure how that would be received.

**Comment by rockrider85fp** [comment]
@DanMcInerney first of all, thank you for your work.

I'll start by saying: sorry for my english :)

Let me tell you how I reached this thread.

From 2016 to 2017, I haven't been able to use Wi-Fi at all. Neither my neighbors. The word is that some radio amateur enthusisastic neighbour (using large antennas on the top of the building) was causing deliberate interference killing all AP's on the street. So, at the time, I decided to call the spectrum regulator authority to come and check the situation. They inspected his installation, and found nothing irregular. Then they came to my house to perform a spectrum monitoring on the 2.4 GHz frequency band. Everything was ok also. By "ok" they meant that, in what refers to spectral activity, all signals were normal, and that frequency band shown a normal behavior, considering that it is an ISM band). Still, I was able to prove them that I couldn't use my wifi network, since the connection keeped on droping. They told me: "Well, moove to 5 GHz"... which I did.

So I decided to google a little bit, and I discovered the power of Wireshark in linux. So after setting up the right filters (ah, almost forget, I bought an ALFA network card), I was able to see a lot of deauth messages being sent. Of course, I had to google on that phenomenon. So the thing is:
- There is someone deauthenticating on a 24/7 basis for the last two years. Possibly using this script.
- It hops from channel to channel (I've confirmed that on Wireshark)
- All deauth packets show Sequence Number SN=0.

My problem is: from last week this started happening in 5 GHz also! So, like always, I've googled for: Deauth attack and 5 GHz, which brought me to this page. So I am wondering, can this guy be using @MisterBianco script, instead?

I'm so nervous about this that I bought a directive antenna, so I can apply some Direction Finding techniques that I've read about in another site. If I can locate him... I haven't thought about that yet 📦 
Now I have a 10 m ethernet cable passing from the AP in the living room to my bedroom. Seems like the 90's, WTF?!

Any help will me very much appreciated. 

PS- The cool side of this story is that I found the Marvelous Power of Kali and ALFA!


So the situation is:

**Comment by rockrider85fp** [comment]
Dear all, hope you're good.

MisterBianco, I'm very sorry for this late reply. Here's what happened:

After writing my previous message, describing the situation, all of a sudden the atack ceased...

In my opinion, the person doing it, follows this thread...

Why am I writting today? Because it started again yesterday. If the person doing this is reading this post, please Stop It. No one in our street can have Wi-Fi because of you, and this lasts for 2 years! Stop IT!

Mister Bianco thankyou for your support. I just have to say that I tried your script and couldn't use it due to an error saying "no module named pyric.pyw". I'am a total newbie and I could'nt make it work, neither find an answer on google.

Thank you for all

**Comment by vuong244** [comment]
Which Alfa do you use for 5ghz injection?

**Comment by ahmadkar** [comment]
These comments are making me laugh out very very hard  xD
