### ISSUE TITLE
case problem

### ISSUE THREAD

**Issue by AnthonyAaronHughWong** [DanMcInerney/wifijammer#31]
the skip function sometimes doesn't work. I get the code slightly modified so that mac address is always stored in lower case, and the problem seems gone.

**Comment by DanMcInerney** [comment]
Can I see a PR?

**Comment by AnthonyAaronHughWong** [comment]
i'm not sure what a pr is...

**Comment by AnthonyAaronHughWong** [comment]
pull request?

**Comment by steveno** [comment]
@AnthonyAaronHughWong yes.

**Comment by AnthonyAaronHughWong** [comment]
I just uploaded the code. I really can't guarantee its rightness, because 
I've never uploaded code to github before. You should review it first.

**Comment by DanMcInerney** [comment]
Great, took a look and I think you're 100% right. It'd be cool to give you credit for your work so if you want to submit this as a pull request then it's real simple: https://help.github.com/articles/creating-a-pull-request/

Otherwise I'll just add in your changes myself when I get time sometime in the near future.

**Comment by llazzaro** [comment]
I think you can cherry pick those commits:
https://coderwall.com/p/sgpksw/git-cherry-pick-from-another-repository

good luck

**Comment by DanMcInerney** [comment]
I think I fixed this.
