### ISSUE TITLE
How to install this thing

### ISSUE THREAD

**Issue by captainven** [DanMcInerney/wifijammer#91]
Sorry but im totally new in this openwrt..can you guys tell me how to install this wifi jammer on my openwrt ..thank you <3

**Comment by Th3R3dP1ll** [comment]
Take this with a pinch of salt because I don't have any experience directly with opwrt but if its a linux based distro you should be able to use the CLI to install this directly from github. 

use https://dephace.com/how-to-make-a-wifi-jammer-with-raspberry-pi-3/ as a decent tutorial for installation on a raspberry pi and the principles should be very similar if not the same for your openwrt. 

Hope this helps.

**Comment by WindNinja** [comment]
You don't need to install it, just read the readme file.
